version: '3.8'

services:
    mysql:
        image: mysql:8
        ports:
            - '6033:3306'
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=wp_test
        command: --default-authentication-plugin=mysql_native_password

    wordpress:
        image: wordpress:fpm-alpine
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: test
            WORDPRESS_DB_PASSWORD: test
            WORDPRESS_DB_NAME: wp_test
        volumes:
            - wordpress:/var/www/html

    wp-cli:
        image: wordpress:cli
        depends_on:
            - wordpress
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: test
            WORDPRESS_DB_PASSWORD: test
            WORDPRESS_DB_NAME: wp_test
        volumes:
            - wordpress:/var/www/html
            - ./assets/:/assets/:ro
        dns:
            - 1.1.1.1

volumes:
    wordpress:
    db:
